import type { EvidenceItem } from "./EvidenceQueueList";

export const evidenceData: EvidenceItem[] = [
  {
    id: "EV-2104",
    title: "Access review — Production DB",
    description:
      "Quarterly review of all privileged access to production databases. Includes role assignments and removal log.",
    submitter: { name: "Marcus Liu", initials: "ML", role: "DevOps Lead" },
    department: "Engineering",
    project: "Q1 SOC 2 Audit",
    framework: "SOC 2",
    rule: "CC6.1 — Logical access controls",
    submittedAt: "2 hours ago",
    deadline: "Today, 5:00 PM",
    deadlineUrgent: true,
    priority: "critical",
    status: "pending",
    riskScore: 82,
    duplicate: true,
    files: [
      { name: "access-review-q1.pdf", size: "2.4 MB", type: "pdf" },
      { name: "role-matrix.xlsx", size: "184 KB", type: "sheet" },
    ],
    workflow: 2,
  },
  {
    id: "EV-2103",
    title: "Encryption attestation Q4",
    description: "Vendor-signed attestation that data at rest is AES-256 encrypted across all storage tiers.",
    submitter: { name: "Sara Chen", initials: "SC", role: "Security Eng." },
    department: "Security",
    project: "ISO 27001 Surveillance",
    framework: "ISO 27001",
    rule: "A.10.1 — Cryptographic controls",
    submittedAt: "Yesterday",
    deadline: "Tomorrow",
    deadlineUrgent: false,
    priority: "high",
    status: "pending",
    riskScore: 24,
    duplicate: false,
    files: [{ name: "encryption-attestation-q4.pdf", size: "812 KB", type: "pdf" }],
    workflow: 2,
  },
  {
    id: "EV-2099",
    title: "Vendor SOC report — Stripe",
    description: "Latest SOC 2 Type II report for payment processor. Verify scope covers in-use services.",
    submitter: { name: "Priya Shah", initials: "PS", role: "Vendor Mgmt" },
    department: "Finance",
    project: "Vendor Risk Program",
    framework: "SOC 2",
    rule: "CC9.2 — Vendor management",
    submittedAt: "2 days ago",
    deadline: "Mar 12",
    deadlineUrgent: false,
    priority: "high",
    status: "pending",
    riskScore: 41,
    duplicate: false,
    files: [
      { name: "stripe-soc2-2024.pdf", size: "5.1 MB", type: "pdf" },
      { name: "scope-mapping.docx", size: "96 KB", type: "doc" },
    ],
    workflow: 1,
  },
  {
    id: "EV-2097",
    title: "Backup restoration test log",
    description: "Evidence of successful quarterly restore drill from offsite backups.",
    submitter: { name: "Elena Martins", initials: "EM", role: "Compliance" },
    department: "IT Operations",
    project: "ISO 27001 Surveillance",
    framework: "ISO 27001",
    rule: "A.12.3 — Backup",
    submittedAt: "3 days ago",
    deadline: "Mar 14",
    deadlineUrgent: false,
    priority: "medium",
    status: "reviewed",
    riskScore: 12,
    duplicate: false,
    files: [{ name: "restore-test-log.pdf", size: "1.2 MB", type: "pdf" }],
    workflow: 4,
  },
  {
    id: "EV-2095",
    title: "Incident response tabletop",
    description: "Annual IR tabletop exercise minutes, attendance and lessons learned.",
    submitter: { name: "Marcus Liu", initials: "ML", role: "DevOps Lead" },
    department: "Engineering",
    project: "HIPAA Readiness",
    framework: "HIPAA",
    rule: "§164.308(a)(6) — Security incident",
    submittedAt: "4 days ago",
    deadline: "Mar 18",
    deadlineUrgent: false,
    priority: "medium",
    status: "pending",
    riskScore: 31,
    duplicate: false,
    files: [
      { name: "ir-tabletop-minutes.pdf", size: "640 KB", type: "pdf" },
      { name: "attendance.csv", size: "8 KB", type: "sheet" },
    ],
    workflow: 1,
  },
  {
    id: "EV-2091",
    title: "Endpoint MDM coverage report",
    description: "Snapshot of MDM enrollment across managed laptops with exception list.",
    submitter: { name: "Diego Romero", initials: "DR", role: "IT Admin" },
    department: "IT Operations",
    project: "Q1 SOC 2 Audit",
    framework: "SOC 2",
    rule: "CC6.7 — Endpoint security",
    submittedAt: "5 days ago",
    deadline: "Mar 20",
    deadlineUrgent: false,
    priority: "low",
    status: "flagged",
    riskScore: 67,
    duplicate: true,
    files: [{ name: "mdm-coverage.pdf", size: "1.8 MB", type: "pdf" }],
    workflow: 2,
  },
  {
    id: "EV-2088",
    title: "Data retention policy v3.2",
    description: "Updated policy reflecting new EU customer data residency requirements.",
    submitter: { name: "Sara Chen", initials: "SC", role: "Security Eng." },
    department: "Legal",
    project: "GDPR Renewal",
    framework: "GDPR",
    rule: "Art. 5 — Storage limitation",
    submittedAt: "1 week ago",
    deadline: "Mar 24",
    deadlineUrgent: false,
    priority: "medium",
    status: "reviewed",
    riskScore: 9,
    duplicate: false,
    files: [{ name: "retention-policy-v3.2.pdf", size: "420 KB", type: "pdf" }],
    workflow: 4,
  },
];
